name: CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.8
        options: --privileged
        ports:
          - 8080:8080

    env:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    runs-on: self-hosted 
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull and Deploy Docker Containers
        run: |
          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml up -d --remove-orphans